using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XJector
{
    [Generator]
    public class InjectSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find fields with [Inject] attribute
            var fieldDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsFieldWithAttributes(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m != null);

            var compilationAndClasses = context.CompilationProvider.Combine(fieldDeclarations.Collect());

            context.RegisterSourceOutput(compilationAndClasses,
                static (spc, source) => Execute(source.Right, spc));
        }

        private static bool IsFieldWithAttributes(SyntaxNode node)
        {
            return node is FieldDeclarationSyntax fieldDeclaration && fieldDeclaration.AttributeLists.Count > 0;
        }

        private static InjectableFieldInfo GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var fieldDeclaration = (FieldDeclarationSyntax)context.Node;

            foreach (VariableDeclaratorSyntax variable in fieldDeclaration.Declaration.Variables)
            {
                if (context.SemanticModel.GetDeclaredSymbol(variable) is IFieldSymbol fieldSymbol)
                {
                    bool hasInjectAttribute = fieldSymbol.GetAttributes()
                        .Any(ad => ad.AttributeClass?.Name is "InjectAttribute" or "Inject");

                    if (!hasInjectAttribute)
                    {
                        continue;
                    }
                    
                    var classSymbol = fieldSymbol.ContainingType;
                        
                    return new InjectableFieldInfo
                    {
                        FieldName = fieldSymbol.Name,
                        FieldType = fieldSymbol.Type.ToDisplayString(),
                        ClassName = classSymbol.Name,
                        Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : classSymbol.ContainingNamespace.ToDisplayString(),
                        IsPartial = classSymbol.DeclaringSyntaxReferences
                            .Select(r => r.GetSyntax())
                            .OfType<ClassDeclarationSyntax>()
                            .Any(c => c.Modifiers.Any(m => m.Text == "partial"))
                    };
                }
            }
            return null;
        }

        private static void Execute(System.Collections.Immutable.ImmutableArray<InjectableFieldInfo> fields, SourceProductionContext context)
        {
            if (fields.IsDefaultOrEmpty) return;
            
            var groupedFields = fields.GroupBy(f => new { f.Namespace, f.ClassName, f.IsPartial });

            foreach (var group in groupedFields)
            {
                // Security: if the user forgot "partial", we generate a Roslyn error (the famous red underline in the IDE)
                if (!group.Key.IsPartial)
                {
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor("DI001", "Missing partial modifier", $"Class {group.Key.ClassName} must be 'partial' to use [Inject].", "DependencyInjection", DiagnosticSeverity.Error, true),
                        Location.None);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }
                
                string code = new CodeWriter()
                    .WriteComment("<auto-generated/>")
                    .WriteUsings("UnityEngine", "CCLBStudio.DependencyInjection")
                    .OpenNamespace(group.Key.Namespace)
                    
                    .OpenClass(group.Key.ClassName)
                    .WithInterfaces("IGeneratedInjectable")
                    .WithAccessModifier(CodeWriter.AccessModifier.Public)
                    .WithPartial(true)
                    .Build()
                    
                    .WriteMethod("InjectDependencies")
                    .WithAccessModifier(CodeWriter.AccessModifier.Public)
                    .WithReturnType("void")
                    .WithInstructions(group.Select(field => $"this.{field.FieldName} = XJectorContainer.Resolve<{field.FieldType}>();").ToArray())
                    .Build()
                    
                    .CloseBlock()
                    .CloseNamespace()
                    .Build();

                context.AddSource($"{group.Key.ClassName}_Inject.g.cs", SourceText.From(code, Encoding.UTF8));
            }
        }
    }

    public class InjectableFieldInfo
    {
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string ClassName { get; set; }
        public string Namespace { get; set; }
        public bool IsPartial { get; set; }
    }
}