using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XJector
{
    [Generator]
    public class InjectSourceGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            // Find fields with [Inject] attribute
            var fieldDeclarations = context.SyntaxProvider
                .CreateSyntaxProvider(
                    predicate: static (s, _) => IsFieldWithAttributes(s),
                    transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
                .Where(static m => m != null);

            // Regrouper les champs par classe
            var compilationAndClasses = context.CompilationProvider.Combine(fieldDeclarations.Collect());

            // Générer le code
            context.RegisterSourceOutput(compilationAndClasses,
                static (spc, source) => Execute(source.Right, spc));
        }

        private static bool IsFieldWithAttributes(SyntaxNode node)
        {
            return (node is FieldDeclarationSyntax fieldDeclaration && fieldDeclaration.AttributeLists.Count > 0);
        }

        // Filtre profond (Sémantique)
        private static InjectableFieldInfo GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
        {
            var fieldDeclaration = (FieldDeclarationSyntax)context.Node;

            foreach (VariableDeclaratorSyntax variable in fieldDeclaration.Declaration.Variables)
            {
                // Obtenir le symbole (l'objet sémantique) du champ
                if (context.SemanticModel.GetDeclaredSymbol(variable) is IFieldSymbol fieldSymbol)
                {
                    // Vérifier s'il a notre attribut [Inject]
                    bool hasInjectAttribute = fieldSymbol.GetAttributes()
                        .Any(ad => ad.AttributeClass?.Name is "InjectAttribute" or "Inject");

                    if (!hasInjectAttribute)
                    {
                        continue;
                    }
                    
                    var classSymbol = fieldSymbol.ContainingType;
                        
                    return new InjectableFieldInfo
                    {
                        FieldName = fieldSymbol.Name,
                        FieldType = fieldSymbol.Type.ToDisplayString(),
                        ClassName = classSymbol.Name,
                        Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : classSymbol.ContainingNamespace.ToDisplayString(),
                        IsPartial = classSymbol.DeclaringSyntaxReferences
                            .Select(r => r.GetSyntax())
                            .OfType<ClassDeclarationSyntax>()
                            .Any(c => c.Modifiers.Any(m => m.Text == "partial"))
                    };
                }
            }
            return null;
        }

        // La génération de texte final
        private static void Execute(System.Collections.Immutable.ImmutableArray<InjectableFieldInfo> fields, SourceProductionContext context)
        {
            if (fields.IsDefaultOrEmpty) return;

            // Grouper par classe (au cas où il y a plusieurs [Inject] dans la même classe)
            var groupedFields = fields.GroupBy(f => new { f.Namespace, f.ClassName, f.IsPartial });

            foreach (var group in groupedFields)
            {
                // Security: if the user forgot "partial", we generate a Roslyn error (the famous red underline in the IDE)
                if (!group.Key.IsPartial)
                {
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor("DI001", "Missing partial modifier", $"Class {group.Key.ClassName} must be 'partial' to use [Inject].", "DependencyInjection", DiagnosticSeverity.Error, true),
                        Location.None);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                string namespaceDeclaration = string.IsNullOrEmpty(group.Key.Namespace) 
                    ? "" 
                    : $"namespace {group.Key.Namespace} {{";
                string namespaceClosure = string.IsNullOrEmpty(group.Key.Namespace) ? "" : "}";

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using UnityEngine;");
                sb.AppendLine("using CCLBStudio.DependencyInjection;");
                sb.AppendLine();
                sb.AppendLine(namespaceDeclaration);
                sb.AppendLine($"    public partial class {group.Key.ClassName} : IGeneratedInjectable");
                sb.AppendLine("    {");
                
                // Remplacer "object" par ton vrai type de conteneur, ex: DiContainer
                sb.AppendLine("        public void InjectDependencies()");
                sb.AppendLine("        {");
                //sb.AppendLine("            var diContainer = (DiContainer)container;"); // Cast vers ton vrai conteneur

                foreach (var field in group)
                {
                    // L'injection réelle !
                    sb.AppendLine($"            this.{field.FieldName} = XJectorContainer.Resolve<{field.FieldType}>();");
                }

                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine(namespaceClosure);

                // Ajouter le fichier généré à la compilation
                context.AddSource($"{group.Key.ClassName}_Inject.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }
    }

    public class InjectableFieldInfo
    {
        public string FieldName { get; set; }
        public string FieldType { get; set; }
        public string ClassName { get; set; }
        public string Namespace { get; set; }
        public bool IsPartial { get; set; }
    }
}