using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XJector;

[Generator]
public class ProviderSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsClassWithAttributes(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m != null);
        
        var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());

        // Générer le code
        context.RegisterSourceOutput(compilationAndClasses,
            static (spc, source) => Execute(source.Right, spc));
    }
    
    private static bool IsClassWithAttributes(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration 
               && classDeclaration.AttributeLists.Count > 0
               && classDeclaration.AttributeLists
                   .SelectMany(al => al.Attributes)
                   .Any(attr => attr.Name.ToString() is "Provide" or "ProvideAttribute");
    }
    
    private static ProviderClassInfo GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }
        
        return new ProviderClassInfo
        {
            ClassName = classSymbol.Name,
            Namespace = classSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : classSymbol.ContainingNamespace.ToDisplayString(),
            IsPartial = classSymbol.DeclaringSyntaxReferences
                .Select(r => r.GetSyntax())
                .OfType<ClassDeclarationSyntax>()
                .Any(c => c.Modifiers.Any(m => m.Text == "partial"))
        };
    }
    
    private static void Execute(System.Collections.Immutable.ImmutableArray<ProviderClassInfo> fields, SourceProductionContext context)
        {
            if (fields.IsDefaultOrEmpty) return;

            var groupedFields = fields.GroupBy(f => new { f.Namespace, f.ClassName, f.IsPartial });

            foreach (var group in groupedFields)
            {
                // Security: if the user forgot "partial", we generate a Roslyn error (the famous red underline in the IDE)
                if (!group.Key.IsPartial)
                {
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor("DI001", "Missing partial modifier", $"Class {group.Key.ClassName} must be 'partial' to use [Provide].", "DependencyInjection", DiagnosticSeverity.Error, true),
                        Location.None);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }

                string namespaceDeclaration = string.IsNullOrEmpty(group.Key.Namespace) 
                    ? "" 
                    : $"namespace {group.Key.Namespace} {{";
                string namespaceClosure = string.IsNullOrEmpty(group.Key.Namespace) ? "" : "}";

                var sb = new StringBuilder();
                sb.AppendLine("// <auto-generated/>");
                sb.AppendLine("using UnityEngine;");
                sb.AppendLine("using CCLBStudio.DependencyInjection;");
                sb.AppendLine();
                sb.AppendLine(namespaceDeclaration);
                sb.AppendLine($"    public partial class {group.Key.ClassName}");
                sb.AppendLine("    {");
                
                // Remplacer "object" par ton vrai type de conteneur, ex: DiContainer
                sb.AppendLine("        [RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)]");
                sb.AppendLine("        public static void Provide()");
                sb.AppendLine("        {");
                sb.AppendLine($"            XJectorContainer.Provide(new {group.Key.ClassName}());"); // Cast vers ton vrai conteneur
                
                sb.AppendLine("        }");
                sb.AppendLine("    }");
                sb.AppendLine(namespaceClosure);

                // Ajouter le fichier généré à la compilation
                context.AddSource($"{group.Key.ClassName}_Provide.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
            }
        }
}

public class ProviderClassInfo
{
    public string ClassName { get; set; }
    public string Namespace { get; set; }
    public bool IsPartial { get; set; }
}