using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace XJector;

[Generator]
public class ProviderSourceGenerator : IIncrementalGenerator
{
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDeclarations = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (s, _) => IsClassWithAttributes(s),
                transform: static (ctx, _) => GetSemanticTargetForGeneration(ctx))
            .Where(static m => m != null);
        
        var assemblyName = context.CompilationProvider
            .Select(static (c, _) => c.AssemblyName);
        var combined = assemblyName.Combine(classDeclarations.Collect());
        
        //var compilationAndClasses = context.CompilationProvider.Combine(classDeclarations.Collect());
        
        context.RegisterSourceOutput(combined, static (spc, source) =>
        {
            Execute(source.Left, source.Right, spc);
        });
    }
    
    private static bool IsClassWithAttributes(SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration 
               && classDeclaration.AttributeLists.Count > 0
               && classDeclaration.AttributeLists
                   .SelectMany(al => al.Attributes)
                   .Any(attr => attr.Name.ToString() is "Provide" or "ProvideAttribute");
    }
    
    private static ProviderClassInfo GetSemanticTargetForGeneration(GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol classSymbol)
        {
            return null;
        }
        
        string className = classSymbol.Name;
        string namespaceName = classSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : classSymbol.ContainingNamespace.ToDisplayString();
        bool isPartial = classSymbol.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.Text == "partial"));
        
        return new ProviderClassInfo(className, namespaceName, isPartial);
    }
    
    private static void Execute(string assemblyName, ImmutableArray<ProviderClassInfo> fields, SourceProductionContext context)
        {
            if (fields.IsDefaultOrEmpty)
            {
                EmitReportForEmptyAssembly(assemblyName, context);
                return;
            }

            var groupedFields = fields.GroupBy(f => new { f.Namespace, f.ClassName, f.IsPartial });

            var generatedClasses = new List<string>();

            foreach (var group in groupedFields)
            {
                // Security: if the user forgot "partial", we generate a Roslyn error (the famous red underline in the IDE)
                if (!group.Key.IsPartial)
                {
                    var diagnostic = Diagnostic.Create(
                        new DiagnosticDescriptor("DI001", "Missing partial modifier", $"Class {group.Key.ClassName} must be 'partial' to use [Provide].", "DependencyInjection", DiagnosticSeverity.Error, true),
                        Location.None);
                    context.ReportDiagnostic(diagnostic);
                    continue;
                }
                
                string code = new CodeWriter()
                    .WriteComment("<auto-generated/>")
                    .WriteUsings("UnityEngine", "CCLBStudio.DependencyInjection")
                    .OpenNamespace(group.Key.Namespace)
                    
                    .OpenClass(group.Key.ClassName)
                    .WithAccessModifier(CodeWriter.AccessModifier.Public)
                    .WithPartial(true)
                    .Build()
                    
                    .WriteMethod("Provide")
                    .WithAccessModifier(CodeWriter.AccessModifier.Public)
                    .WithStatic(true)
                    .WithReturnType("void")
                    .WithAttributes("RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)")
                    .WithInstruction($"XJectorContainer.Provide(new {group.Key.ClassName}());")
                    .Build()
                    
                    .CloseBlock()
                    .CloseNamespace()
                    .Build();

                // Ajouter le fichier généré à la compilation
                context.AddSource($"{group.Key.ClassName}_Provide.g.cs", SourceText.From(code, Encoding.UTF8));

                string fullName = string.IsNullOrEmpty(group.Key.Namespace)
                    ? group.Key.ClassName
                    : $"{group.Key.Namespace}.{group.Key.ClassName}";
                generatedClasses.Add(fullName);
            }

            EmitReport(generatedClasses, context);
        }
    
    private static void EmitReportForEmptyAssembly(string assemblyName, SourceProductionContext context)
    {
        context.ReportDiagnostic(Diagnostic.Create(
            new DiagnosticDescriptor(
                "DI101",
                "XJector provider report",
                "No provider generated by XJector for assembly {0}",
                "DependencyInjection",
                DiagnosticSeverity.Warning,
                true),
            Location.None,
            assemblyName));
    }

        private static void EmitReport(List<string> generatedClasses, SourceProductionContext context)
        {
            if (generatedClasses.Count == 0) return;

            generatedClasses.Sort(System.StringComparer.Ordinal);

            // 1. Report visible in the build log (Unity Console window / MSBuild output)
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "DI100",
                    "XJector provider report",
                    "{0} generated provider(s) by XJector : {1}",
                    "DependencyInjection",
                    DiagnosticSeverity.Warning,
                    true),
                Location.None,
                generatedClasses.Count,
                string.Join(", ", generatedClasses)));
        }
}

public class ProviderClassInfo(string ClassName, string Namespace, bool IsPartial)
{
    public string ClassName { get; } = ClassName;
    public string Namespace { get; } = Namespace;
    public bool IsPartial { get; } = IsPartial;
}