using System.Collections.Generic;

namespace XJector;

/// <summary>
/// Provider strategy for a MonoBehaviour: creates a dedicated GameObject at startup,
/// adds the component to it and registers that component in the container.
/// </summary>
public class ProviderForMonoBehaviourBootstrap(string namespaceName, string className, bool dontDestroyOnLoad) : ICodeSource
{
    public string GetCode()
    {
        var instructions = new List<string>
        {
            $"var go = new GameObject(nameof({className}));"
        };

        if (dontDestroyOnLoad)
        {
            instructions.Add("UnityEngine.Object.DontDestroyOnLoad(go);");
        }

        instructions.Add($"XJectorContainer.Provide(go.AddComponent<{className}>());");

        string code = new CodeWriter()
            .Comment("<auto-generated/>")
            .Usings("UnityEngine", "CCLBStudio.DependencyInjection")
            .OpenNamespace(namespaceName)

            .OpenClass(className)
            .Partial()
            .Build()

            .Method("Provide")
            .Static()
            .Attributes("RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)")
            .Instructions(instructions.ToArray())
            .Build()

            .CloseBlock()
            .CloseNamespace()
            .Build();

        return code;
    }
}
