namespace XJector;

public class ProviderForClassWithEmptyConstructor(string namespaceName, string className) : ICodeSource
{
    public string GetCode()
    {
        string code = new CodeWriter()
            .Comment("<auto-generated/>")
            .Usings("UnityEngine", "CCLBStudio.DependencyInjection")
            .OpenNamespace(namespaceName)
                    
            .OpenClass(className)
            .Partial()
            .Build()
                    
            .Method("Provide")
            .Static()
            .Attributes("RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)")
            .Instruction($"XJectorContainer.Provide(new {className}());")
            .Build()
                    
            .CloseBlock()
            .CloseNamespace()
            .Build();
        
        return code;
    }
}