namespace XJector;

/// <summary>
/// Provider strategy for a ScriptableObject: loads the asset located at the given Resources path
/// and registers that asset instance in the container, so the project asset itself is provided.
/// </summary>
public class ProviderForScriptableObject(string namespaceName, string className, string resourcesPath) : ICodeSource
{
    public string GetCode()
    {
        string escapedPath = resourcesPath.Replace("\\", "\\\\").Replace("\"", "\\\"");

        var writer = new CodeWriter()
            .Comment("<auto-generated/>")
            .Usings("UnityEngine", "CCLBStudio.DependencyInjection")
            .OpenNamespace(namespaceName)

            .OpenClass(className)
            .Partial()
            .Build()

            .Method("Provide")
            .Static()
            .Attribute("RuntimeInitializeOnLoadMethod(RuntimeInitializeLoadType.BeforeSceneLoad)")
            .Instruction($"var asset = Resources.Load<{className}>(\"{escapedPath}\");")
            .If("asset == null", [
                $"Debug.LogError(\"[XJector] Could not load ScriptableObject of type {className} at Resources path '{escapedPath}'.\");",
                "return;"
            ])
            .Instruction("XJectorContainer.Provide(asset);")
            .Build();

        return writer
            .CloseClass()
            .CloseNamespace()
            .Build();
    }
}
