namespace XJector;

/// <summary>
/// Provider strategy for a MonoBehaviour that registers itself in the container during a
/// Unity lifecycle event. Always generates a public <c>XJectorRegister()</c> method. When the user
/// does not already define the chosen lifecycle method, that method is generated and calls
/// <c>XJectorRegister()</c> automatically; otherwise the user is expected to call it themselves.
/// </summary>
public class ProviderForMonoBehaviourSelfRegister(
    string namespaceName,
    string className,
    string eventName,
    bool userDefinesEvent) : ICodeSource
{
    public string GetCode()
    {
        var writer = new CodeWriter()
            .Comment("<auto-generated/>")
            .Usings("UnityEngine", "CCLBStudio.DependencyInjection")
            .OpenNamespace(namespaceName)

            .OpenClass(className)
            .Partial()
            .Build()

            .Method("XJectorRegister")
            .Public()
            .Instruction("XJectorContainer.Provide(this)")
            .Build();

        if (!userDefinesEvent)
        {
            writer = writer
                .Method(eventName)
                .Private()
                .Instruction("XJectorRegister()")
                .Build();
        }

        return writer
            .CloseBlock()
            .CloseNamespace()
            .Build();
    }
}
