using System.Collections.Generic;
using System.Linq;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace XJector.Extensions;

public static class Extensions
{
    public static bool IsClassWithProvideAttribute(this SyntaxNode node)
    {
        return node is ClassDeclarationSyntax classDeclaration 
               && classDeclaration.AttributeLists.Count > 0
               && classDeclaration.AttributeLists
                   .SelectMany(al => al.Attributes)
                   .Any(attr => attr.Name.ToString() is "Provide" or "ProvideAttribute");
    }
    
    public static ProviderKind GetProviderKind(this INamedTypeSymbol typeSymbol)
    {
        for (var baseType = typeSymbol.BaseType; baseType != null; baseType = baseType.BaseType)
        {
            switch (baseType.ToDisplayString())
            {
                case "UnityEngine.MonoBehaviour":
                    return ProviderKind.MonoBehaviour;
                case "UnityEngine.ScriptableObject":
                    return ProviderKind.ScriptableObject;
            }
        }

        return ProviderKind.PlainClass;
    }

    public static ProviderClassInfo GetSemanticTargetForGeneration(this GeneratorSyntaxContext context)
    {
        var classDeclaration = (ClassDeclarationSyntax)context.Node;
        if (context.SemanticModel.GetDeclaredSymbol(classDeclaration) is not INamedTypeSymbol typeSymbol)
        {
            return null;
        }
        
        string className = typeSymbol.Name;
        string namespaceName = typeSymbol.ContainingNamespace.IsGlobalNamespace ? string.Empty : typeSymbol.ContainingNamespace.ToDisplayString();
        bool isPartial = typeSymbol.DeclaringSyntaxReferences
            .Select(r => r.GetSyntax())
            .OfType<ClassDeclarationSyntax>()
            .Any(c => c.Modifiers.Any(m => m.Text == "partial"));

        ProviderKind kind = typeSymbol.GetProviderKind();

        var provideAttribute = typeSymbol.GetAttributes()
            .FirstOrDefault(a => a.AttributeClass?.Name is "ProvideAttribute" or "Provide");

        int monoStrategy = provideAttribute.GetIntArgument("MonoStrategy");
        int registerOn = provideAttribute.GetIntArgument("RegisterOn");
        bool dontDestroyOnLoad = provideAttribute.GetBoolArgument("DontDestroyOnLoad", true);
        string resourcesPath = provideAttribute.GetStringArgument("ResourcesPath");

        string eventName = RegistrationEventName(registerOn);
        bool userDefinesEvent = typeSymbol.GetMembers(eventName).OfType<IMethodSymbol>().Any();

        return new ProviderClassInfo(className, namespaceName, isPartial)
        {
            Kind = kind,
            MonoStrategy = monoStrategy,
            RegisterOn = registerOn,
            DontDestroyOnLoad = dontDestroyOnLoad,
            ResourcesPath = resourcesPath,
            EventName = eventName,
            UserDefinesEvent = userDefinesEvent
        };
    }
    
    private static string RegistrationEventName(int registerOn) => registerOn switch
    {
        1 => "OnEnable",
        2 => "Start",
        _ => "Awake"
    };

    #region Reports

    extension(SourceProductionContext context)
    {
        public void EmitEmptyAssemblyReport(string assemblyName, Location location)
        {
            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "DI101",
                    "XJector provider report",
                    "No provider generated by XJector for assembly {0}",
                    "DependencyInjection",
                    DiagnosticSeverity.Warning,
                    true),
                location,
                assemblyName));
        }

        public void EmitGeneratedProvidersReport(List<string> generatedClasses, Location location)
        {
            if (generatedClasses.Count == 0) return;

            generatedClasses.Sort(System.StringComparer.Ordinal);

            context.ReportDiagnostic(Diagnostic.Create(
                new DiagnosticDescriptor(
                    "DI100",
                    "XJector provider report",
                    "{0} generated provider(s) by XJector : {1}",
                    "DependencyInjection",
                    DiagnosticSeverity.Warning,
                    true),
                location,
                generatedClasses.Count,
                string.Join(", ", generatedClasses)));
        }
    }

    #endregion
    
    extension(AttributeData attribute)
    {
        public int GetIntArgument(string name, int defaultValue = 0)
        {
            if (attribute == null) return defaultValue;
        
            foreach (var arg in attribute.NamedArguments)
            {
                if (arg.Key == name && arg.Value.Value != null)
                {
                    return System.Convert.ToInt32(arg.Value.Value);
                }
            }
            return defaultValue;
        }

        public bool GetBoolArgument(string name, bool defaultValue = false)
        {
            if (attribute == null) return defaultValue;
        
            foreach (var arg in attribute.NamedArguments)
            {
                if (arg.Key == name && arg.Value.Value is bool b)
                {
                    return b;
                }
            }
            return defaultValue;
        }

        public string GetStringArgument(string name)
        {
            if (attribute == null) return null;
        
            foreach (var arg in attribute.NamedArguments)
            {
                if (arg.Key == name && arg.Value.Value is string s)
                {
                    return s;
                }
            }
            return null;
        }
    }
}